server:
  port: 8084

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ORDER-SERVICE
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/eurekaorder?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul
    show-sql: true







#server:
#  servlet:
#    contextPath:  /auth







